### ISSUE TITLE
Events for game ending

### ISSUE THREAD

**Issue by russelhampton05** [russelhampton05/fin-pong#10]
The existing game should have a max score added to fire an event for winner. This will be what triggers a FB write to record scores. How much the player won by and how fast they won will be the metrics that decide placement on leaderboards.

**Comment by russelhampton05** [comment]
@monicaktran I assigned this to you in case you actually wanted to do some angular and not just all FB. Feel free to swap off this or reassign anything to anyone.

**Comment by monicaktran** [comment]
@russelhampton05 Actually, how about I build the login screen and the high scores screen? That way I can integrate those with Firebase more easily

**Comment by vandersmissenc** [comment]
Looks like we changed from AngularJS to Angular 2. I am going to throw away that branch and start working in the new project. We need to ensure we are better communicating when this occurs so we don't have to throw away work.

**Comment by vandersmissenc** [comment]
No timer, just score. It's ready to be picked integrated for write and read.
